% Credit: https://drive.google.com/drive/folders/18XZ3T8iQ1MzVMngPpcYfKfxNLCJTCkb_

function [coupler_angle] = CouplerAngle(theta, psi, alpha, beta, gamma, eta)
    % **Use sind/cosd/tand to calculate.**
    cos_phi = (sind(beta).*cosd(theta).*cosd(gamma).*cosd(psi)+...
        cosd(theta).*sind(gamma).*cosd(beta)+...
        sind(beta).*sind(theta).*sind(psi)-...
        sind(alpha).*cosd(eta))./...
        (cosd(alpha).*sind(eta));

    sin_phi = (-sind(beta).*sind(theta).*cosd(gamma).*cosd(psi)-...
        sind(theta).*sind(gamma).*cosd(beta)+...
        sind(beta).*cosd(theta).*sind(psi))./...
        sind(eta);

    coupler_angle = atan2d(sin_phi,cos_phi);
end