function [matrix] = dh_link(theta,alpha,rx,dz,angle)

if angle == "d"
    matrix = [
        cosd(theta) -sind(theta)*cosd(alpha) sind(theta)*sind(alpha) rx*cosd(theta);...
        sind(theta) cosd(theta)*cosd(alpha) -cosd(theta)*sind(alpha) rx*sind(theta);...
        0 sind(alpha) cosd(alpha) dz;...
        0 0 0 1 ...
    ];
end
if angle == "r"
    matrix = [
        cos(theta) -sin(theta)*cos(alpha) sin(theta)*sin(alpha) rx*cos(theta);...
        sin(theta) cos(theta)*cos(alpha) -cos(theta)*sin(alpha) rx*sin(theta);...
        0 sin(alpha) cos(alpha) dz;...
        0 0 0 1 ...
    ];
end
matrix = vpa(matrix);
end